name: coregs-env
channels:
  - conda-forge
  - gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - argcomplete=1.12.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=21.4.0
  - backcall=0.2.0
  - blas=2.11
  - bleach=4.1.0
  - boto3=1.20.24
  - botocore=1.23.24
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.2.1
  - cached-property=1.5.2
  - cairo=1.14.12
  - cchardet=2.1.7
  - certifi=2021.10.8
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - coincbc=2.10.5
  - colorama=0.4.4
  - cryptography=36.0.0
  - cycler=0.11.0
  - datapackage=1.15.2
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.4
  - entrypoints=0.3
  - et_xmlfile=1.1.0
  - expat=2.4.4
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fribidi=1.0.10
  - future=0.18.2
  - giflib=5.2.1
  - glib=2.63.1
  - glpk=4.65
  - gmp=6.2.1
  - gmpy2=2.1.2
  - graphite2=1.3.14
  - graphviz=2.40.1
  - greenlet=1.1.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - iam-units=2021.11.12
  - icu=58.2
  - idna=3.3
  - ijson=3.1.4
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - ipykernel=6.4.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isodate=0.6.0
  - jedi=0.18.1
  - jinja2=3.0.2
  - jmespath=0.10.0
  - joblib=1.1.0
  - jpeg=9d
  - jsonlines=2.0.0
  - jsonpointer=2.1
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.9.1
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.2
  - lcms2=2.12
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20210910
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - libxslt=1.1.34
  - linear-tsv=1.1.0
  - lxml=4.7.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - multiprocess=0.70.12.2
  - munkres=1.1.4
  - nbclient=0.5.11
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - networkx=2.6.3
  - nose=1.3.7
  - notebook=6.4.8
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openpyxl=3.0.9
  - openssl=1.1.1m
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - pango=1.42.4
  - parso=0.8.3
  - pathos=0.2.8
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pint=0.18
  - pip=21.2.2
  - pixman=0.40.0
  - ply=3.11
  - pox=0.3.0
  - ppft=1.6.6.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pyam=1.3.1
  - pycparser=2.21
  - pydoe=0.3.8
  - pygments=2.11.2
  - pymysql=1.0.2
  - pyodbc=4.0.32
  - pyomo=5.5.1
  - pyomo.extras=3.3
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyro4=4.82
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.3
  - python-dateutil=2.8.2
  - python-graphviz=0.16
  - python_abi=3.7
  - pytz=2021.3
  - pyutilib=5.8.0
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.2.2
  - qtpy=1.11.2
  - readline=7.0
  - requests=2.27.1
  - rfc3986=1.4.0
  - s3transfer=0.5.0
  - salib=1.4.5
  - scipy=1.7.3
  - seaborn=0.11.2
  - send2trash=1.8.0
  - serpent=1.40
  - setuptools=58.0.4
  - setuptools-scm=6.3.2
  - setuptools_scm=6.3.2
  - sip=4.19.8
  - six=1.16.0
  - sqlalchemy=1.4.27
  - sqlite=3.33.0
  - sympy=1.9
  - tableschema=1.20.2
  - tabulate=0.8.9
  - tabulator=1.53.5
  - terminado=0.13.1
  - testpath=0.5.0
  - tk=8.6.11
  - tomli=1.2.2
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - unicodecsv=0.14.1
  - unixodbc=2.3.9
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xlrd=2.0.1
  - xlsxwriter=3.0.2
  - xlwt=1.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
